<?php
/**
 * Created by PhpStorm.
 * User: 顾力华
 * Date: 2018/6/28
 * Time: 22:36
 */

namespace app\admin\controller;

use app\model\admin;
use Vendor\geetest\GeetestLib;
use think\Config;
use think\Controller;
use think\Session;

class Login extends Controller
{
    public  $config=[];
    public  $data=[];
    function  _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->config=Config::get('geetest');
        Vendor('geetest.GeetestLib#class');
        $this->data= array(
            "user_id" => "jw_user", # 网站用户id
            "client_type" => "web", #web:电脑上的浏览器；h5:手机上的浏览器，包括移动应用内完全内置的web_view；native：通过原生SDK植入APP应用的方式
            "ip_address" => "127.0.0.1" # 请在此处传输用户请求验证时所携带的IP
        );
        }

    function index()
    {

        if (request()->post()) {
            $username = input('username');
            $password = input('password');
            $captcha = input('captcha');
            $ip = get_client_ip(0);
            $date = date("y-m-d h:i:sa");
            $lg_result = admin::login($username, $password, $ip, $date);

            if ($lg_result) {

                Session::set('islogin', 1);
                return alert_success('提示', '登陆成功', 'admin/index/index');
                // return $this->success('a','admin/index/index');
            } else {
                return alert_fail_url('账户或密码错误');


            }
        }
        return $this->fetch('index');

    }
    function loginout(){
        Session::set('islogin', 0);
        echo alert_success('提示','退出成功','admin/login/index');
    }

    function geetest_show_verify()
    {
        $gtSdk=new   GeetestLib( $this->config['geetest_id'],$this->config['geetest_key']);

        $status=$gtSdk->pre_process($this->data,1);
        Session::set('gtserver',$status);
        Session::set('user_id',$this->data['user_id']);
        echo $gtSdk->get_response_str();
    }

    function  geetest_check(){
        $gtSdk=new   GeetestLib( $this->config['geetest_id'],$this->config['geetest_key']);

        if (Session::get('gtserver')==1) {   //服务器正常
            $result = $gtSdk->success_validate($_POST['geetest_challenge'], $_POST['geetest_validate'], $_POST['geetest_seccode'], $this->data);
            if ($result) {
                echo '{"status":"success"}';
            } else {
                echo '{"status":"fail"}';
            }
        } else {  //服务器宕机,走failback模式
            if ($gtSdk->fail_validate($_POST['geetest_challenge'], $_POST['geetest_validate'], $_POST['geetest_seccode'])) {
                echo '{"status":"success"}';
            } else {
                echo '{"status":"fail"}';
            }
        }

    }

}